# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# A guide on how to configure the plugin can be found in the official documentation.
# https://docs.hardservices.xyz/
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

heartItem:
  enabled: true
  name: "&7&lDodaje &41❤ &8(&cmax 15❤&8)"
  material: "GRAY_DYE"
  lore:
    - "&7Po kliknięciu otrzymasz &41❤ !"
    - " "
    - "&cTen przedmiot można użyć tylko"
    - "&cjeśli masz poniżej &415❤"
  loseChance: 50
  addLimit: 0
  withdraw-enabled: true
  drop:
    mode: "never"

reviveBook:
  enabled: true
  name: "&c&LKsiążka odrodzenia"
  material: "ENCHANTED_BOOK"
  inventory-title: "&a&lOdrodz gracza!"
  lore:
    - "&7Odradza wybranego gracza!"
    - " "
    - " &a&oKliknij aby użyć księgi"
  skull-lore:
    - "&7Naciśnij aby odrodzić gracza."
  unbreakable: false

killHeartLimit: 0
removeHeartOnlyIfKilledByPlayer: false
banOn0Hearts: true
broadcastBanFrom0Hearts: true
banTime: 0
reviveHeartAmount: 20


recipe:
  enabled: true
  recipes:
    1:
      recipe-enabled: true
      item: "extra_heart"
      shaped: true
      extraHeartItemUseSuccess: 100
      discover: false
      items:
        - "DIAMOND_BLOCK"
        - "DIAMOND_BLOCK"
        - "DIAMOND_BLOCK"
        - "DIAMOND_BLOCK"
        - "NETHER_STAR"
        - "DIAMOND_BLOCK"
        - "DIAMOND_BLOCK"
        - "DIAMOND_BLOCK"
        - "DIAMOND_BLOCK"
    2:
      recipe-enabled: true
      item: "revive_book"
      shaped: true
      discover: true
      items:
        - "TOTEM_OF_UNDYING"
        - "TOTEM_OF_UNDYING"
        - "TOTEM_OF_UNDYING"
        - "ENCHANTED_GOLDEN_APPLE"
        - "BOOK"
        - "ENCHANTED_GOLDEN_APPLE"
        - "TOTEM_OF_UNDYING"
        - "TOTEM_OF_UNDYING"
        - "TOTEM_OF_UNDYING"


loot:
  enabled: true
  worlds:
    world:
      chanceForHeartToGenerate: 50
      heartAddChance: 50
      chanceForReviveBookToGenerate: 50
    world_nether:
      chanceForHeartToGenerate: 75
      heartAddChance: 75
      chanceForReviveBookToGenerate: 75
    world_the_end:
      chanceForHeartToGenerate: 100
      heartAddChance: 100
      chanceForReviveBookToGenerate: 100

messages:
  heartReceived: "&aOtrzymałeś dodatkowe serce!"
  heartGained: "&aZdobyłeś serce za zabicie gracza ${player}!"
  heartFailure: "&4Nie dostałeś dodatkowego serca."
  heartLost: "&4Straciłeś serce."
  noMoreHeartsBan: "&cStraciliście wszystkie serca."
  bannedNoMoreHeartsBroadcast: "&c${player} &4stracił wszystkie serca."
  configReloaded: "&aKonfiguracja przeładowana."
  recipesReloaded: "&aPrzepisy przeładowane."
  lootReloaded: "&aPrzeładowano ustawienia łupów."
  heartRemoved: "&4Ktoś odebrał Ci ${amount}x serc."
  heartRemovedAdmin: "&4Wziąłeś ${amount}x serca od ${player}."
  heartAdded: "&aKtoś dodał do Ciebie ${amount}x serc."
  heartAddedAdmin: "&aDodałeś ${amount}x kier dla ${player}."
  heartSetted: "&fKtoś nastawił twoje serce na ${amount}x."
  heartSettedAdmin: "&fUstawiasz liczbę serc na ${amount}x fla ${player}."
  heartCheck: "&e${player} ma ${amount}x serc."
  banRemoved: "&aUsunąłeś bana z ${player}."
  playerNotFound: "&cGracz nieodnaleziony."
  playerNotBanned: "&c${player} nie jest zablokowany."
  playerNotDead: "&c${player} nie został wyeliminowany, więc nie można go wskrzesić."
  playerRevived: "&aOdrodziłeś &6${player}&a!"
  maxHeartsFromExtraHeart: "&cNie możesz zdobyć więcej niż ${max}x serc z dodatkowego serca."
  maxHearts: "&cNie możesz zdobyć więcej niż ${max}x serc."
  previousPage: "&a← Poprzednia strona"
  previousPageLore: "&aKliknij, aby wrócić do strony ${page}."
  currentPage: "&7Strona ${currentPage} z ${maxPage}"
  currentPageLore: "&7Aktualnie przeglądasz stronę ${page}."
  nextPage: "&aNastępna strona →"
  nextPageLore: "&aKliknij, aby przejść dalej do strony ${page}."
  urNotPlayer: "&cMusisz być graczem, aby z tego korzystać."
  featureDisabled: "&cTa funkcja jest wyłączona."
  heartWithdrawn: "&aWypłaciłeś serce."
  abuseDetected: "&cNasz system wykrył, że liczba serc jest wyższa niż maksymalna. Przywróciliśmy wasze serca do normalnej wartości."
  altFarmingIgnore: "&cNasz system wykrył, że ${killed} jest Twoim drugim kontem stworzonym do farmowania serc. Nie dodano ani nie usunięto serc. Czy uważacie, że to pomyłka? Skontaktuj się z właścicielem serwera."
  maxHeartsDropped: "&cOsiągnąłeś limit serca. Serce zdobyte za zabicie gracza ${player} zostało usunięte."

placeholder-api:
  banned-text: "&c&lZablokowanty."
  not-banned-text: "&a&lOdblokowany."

custom-commands:
  mode: "disabled"
  onBan:
    - "tellraw @a ${player} got banned!"
  onRevive:
    - "tellraw @a ${revived} got revived by ${reviving}!"

security:
  alt-farming:
    ip-check: true
  limits:
    auto-revert: true