name: HardCode-LifeStealSMP
version: '1.0'
main: me.hardcode.lifestealsmp.Main
api-version: 1.18
authors: [ TheKoteczek ]
description: Plugin on lifestealsmp
website: https://discord.gg/Xf4FtryrWp
softdepend:
  - PlaceholderAPI